### PR TITLE
advent of code

### PR DESCRIPTION
**Pull request by datamucho**

### CODE REVIEW

**Comment by aniervs** [comment]
can you exclude the input files?
Also, can you tell me why all your codes are named `task2-*`?

**Comment by aniervs** [comment]
Cc @datamucho

**Comment by datamucho** [comment]
I though it was task<day>-<num>
Day 2 task 1
Task2-1

**Comment by aniervs** [comment]
Screenshot 2024-02-07 at 14 48 48

**Review by aniervs — APPROVED** [review]

**Pull request merged**
