### PR TITLE
Nikolai's folder added

### PR DESCRIPTION
**Pull request by alukan**

### CODE REVIEW

**Review by aniervs — CHANGES_REQUESTED** [review]
Please delete these files from pycharm (the .idea/ folder).
You can do that by modifying the .gitignore file.

**Comment by alukan** [comment]
sorry for this mistake, now it should be ok

**Comment by aniervs** [comment]
can you exclude the input files?

**Comment by alukan** [comment]
deleted

**Comment by aniervs** [comment]
cool. Just add the solutions to the functions assignments in the given Jupyter notebook, and that's all.

**Comment by alukan** [comment]
done

**Review by aniervs — APPROVED** [review]

**Pull request merged**
